version: '3.8'

services:
  postgres:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - redis-network

  redis:
    image: "redis:latest"
    container_name: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge

