AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an RabbitMQ and RDS instances.

Parameters:
  RDSPASSWORD:
    Type: String
    NoEcho: true

Resources:

  RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for RDS instance'
      VpcId: 'vpc-067d20803efece1e3'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: '0.0.0.0/0'

  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: "discord-bot-rds-db"
      DBName: 'tempo'
      MasterUsername: adminwhatup
      MasterUserPassword: !Ref RDSPASSWORD
      DBInstanceClass: 'db.t3.micro'
      AllocatedStorage: '20'
      Engine: 'postgres'
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: 'gp2'

  RDSSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Subnet group for RDS instance'
      SubnetIds:
        - 'subnet-0edcb814af0d6a907'
        - 'subnet-03cd93093acf98fa6'

Outputs:

  RDSInstanceEndpoint:
    Description: "The endpoint address of the RDS instance"
    Value: !GetAtt RDSInstance.Endpoint.Address

  RDSInstanceArn:
    Description: "The ARN of the RDS instance"
    Value: !Ref RDSInstance
